name: Daily and Manual Commit Workflow

on:
  # Schedule to run daily at 12:00 PM UTC
  schedule:
    - cron: '0 12 * * *'
  # Enable manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Add a commit with your email in the step name
      - name: Commit Changes by 23f3001356@ds.study.iitm.ac.in
        run: |
          echo "Daily commit on $(date)" >> daily-log.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "23f3001356@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily commit by GitHub Actions"
          git push
